```javascript
// Script.js:[cite: 1]

let btn = document.querySelector("#btn")[cite: 1]
let content = document.querySelector("#content")[cite: 1]
let voice = document.querySelector("#voice")[cite: 1]

function speak(text) {[cite: 1]
    let text_speak = new SpeechSynthesisUtterance(text)[cite: 1]
    text_speak.rate = 1[cite: 1]
    text_speak.pitch = 1[cite: 1]
    text_speak.volume = 1[cite: 1]
    text_speak.lang = "hi-GB"[cite: 1]
    window.speechSynthesis.speak(text_speak)[cite: 1]
}[cite: 1]

function wishMe() {[cite: 1]
    let day = new Date()[cite: 1]
    let hours = day.getHours()[cite: 1]
    if (hours >= 0 && hours < 12) {[cite: 1]
        speak("Good Morning Sir")[cite: 2]
    } else if (hours >= 12 && hours < 16) {[cite: 2]
        speak("Good afternoon Sir")[cite: 2]
    } else {[cite: 2]
        speak("Good Evening Sir")[cite: 2]
    }[cite: 2]
}[cite: 2]

// window.addEventListener('load',()=>{}[cite: 2]
//     wishMe()[cite: 2]
// })[cite: 2]

let speechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition[cite: 2]
let recognition = new speechRecognition()[cite: 2]

recognition.onresult = (event) => {[cite: 2]
    let currentIndex = event.resultIndex[cite: 2]
    let transcript = event.results[currentIndex][0].transcript[cite: 2]
    content.innerText = transcript[cite: 2]
    takeCommand(transcript.toLowerCase())[cite: 2]
}[cite: 3]

btn.addEventListener("click", () => {[cite: 3]
    recognition.start()[cite: 3]
    voice.style.display = "block"[cite: 3]
    btn.style.display = "none"[cite: 3]
})[cite: 3]

function takeCommand(message) {[cite: 3]
    voice.style.display = "none"[cite: 3]
    btn.style.display = "flex"[cite: 3]
    if (message.includes("hello") || message.includes("hey")) {[cite: 3]
        speak("hello sir,what can i help you?")[cite: 3]
    } else if (message.includes("how are you")) {[cite: 3]
        speak("i am fine what about you")[cite: 3]
    } else if (message.includes("assalamu alaikum")) {[cite: 3]
        speak("wa alaykum s-salamu")[cite: 3]
    } else if (message.includes("who are you")) {[cite: 3]
        speak("i am AI assistant ,created by Aafiya Khan")[cite: 4]
    } else if (message.includes("open youtube")) {[cite: 4]
        speak("opening youtube...")[cite: 4]
        window.open("https://youtube.com/", "_blank")[cite: 4]
    } else if (message.includes("open google")) {[cite: 4]
        speak("opening google...")[cite: 4]
        window.open("https://google.com/", "_blank")[cite: 4]
    } else if (message.includes("open facebook")) {[cite: 4]
        speak("opening facebook...")[cite: 4]
        window.open("https://facebook.com/", "_blank")[cite: 4]
    } else if (message.includes("open instagram")) {[cite: 4]
        speak("opening instagram...")[cite: 4]
        window.open("https://instagram.com/", "_blank")[cite: 4]
    } else if (message.includes("open calculator")) {[cite: 4]
        speak("opening calculator..")[cite: 4]
        window.open("calculator://")[cite: 4]
    } else if (message.includes("open whatsapp")) {[cite: 4]
        speak("opening whatsapp..")[cite: 4]
        window.open("whatsapp://")[cite: 5]
    } else if (message.includes("time")) {[cite: 5]
        let time = new Date().toLocaleString(undefined, { hour: "numeric", minute: "numeric" })[cite: 5]
        speak(time)[cite: 5]
    } else if (message.includes("date")) {[cite: 5]
        let date = new Date().toLocaleString(undefined, { day: "numeric", month: "short" })[cite: 5]
        speak(date)[cite: 5]
    } else {[cite: 5]
        let finalText = "this is what i found on internet regarding" + message.replace("shipra", "") || message.replace("shipra", "")[cite: 5]
        speak(finalText)[cite: 5]
        window.open(`https://www.google.com/search?q=${message.replace("shipra","")}`, "_blank")[cite: 5]
    }[cite: 5]
}[cite: 5]

```